version: '3.8'
services:
  php-apache-environment:
    volumes:
      - ./src:/var/www/html/
    ports:
      - 3000:80
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - sqlDate:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  sqlDate: null
